%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters (scaled to 640×480)
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# --- Intrinsics (scaled from original 1920×1080 to 640×480) ---
Camera1.fx: 319.887037   # 959.661112 × (640/1920)
Camera1.fy: 426.419323   # 959.693478 × (480/1080)
Camera1.cx: 319.795145   # 959.385435 × (640/1920)
Camera1.cy: 239.792711   # 539.533360 × (480/1080)

# --- Distortion (unchanged) ---
Camera1.k1: -0.000591
Camera1.k2:  0.000519
Camera1.p1:  0.000001
Camera1.p2: -0.000030
Camera1.k3:  0.000000

# Camera frames per second
Camera.fps: 30

# Color order (0: BGR, 1: RGB; ignored if grayscale)
Camera.RGB: 1

# Camera resolution
Camera.width:  640
Camera.height: 480

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
ORBextractor.nFeatures:    1000
ORBextractor.scaleFactor:  1.2
ORBextractor.nLevels:      8
ORBextractor.iniThFAST:    20
ORBextractor.minThFAST:    7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize:      0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth:    0.9
Viewer.PointSize:         2.0
Viewer.CameraSize:        0.08
Viewer.CameraLineWidth:   3.0
Viewer.ViewpointX:        0.0
Viewer.ViewpointY:
